# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20160102_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='deleteGame',
            field=models.BooleanField(default=False),
        ),
    ]
