# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_game_deletegame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='games'),
        ),
    ]
