# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_auto_20160124_0635'),
    ]

    operations = [

    ]