# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0012_game_cropping'),
    ]

    operations = [
    ]
