# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20160128_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='games'),
        ),
    ]
