# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_remove_game_cropping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='deleteGame',
            new_name='delete',
        ),
    ]
